
CREATE SEQUENCE "SEQ_CLIENTE"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "SEQ_CLIENTE"
  OWNER TO postgres;

CREATE SEQUENCE "SEQ_INTERACAO"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "SEQ_INTERACAO"
  OWNER TO postgres;

CREATE SEQUENCE "SEQ_PRODUTO"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "SEQ_PRODUTO"
  OWNER TO postgres;

CREATE SEQUENCE "SEQ_VENDA"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "SEQ_VENDA"
  OWNER TO postgres;
 
CREATE SEQUENCE "SEQ_VENDA_ITEM"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "SEQ_VENDA_ITEM"
  OWNER TO postgres;
  
  CREATE TABLE "CLIENTE"
(
  "ID_CLIENTE" integer NOT NULL DEFAULT nextval('"SEQ_CLIENTE"'::regclass),
  "NOME" character(30),
  CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("ID_CLIENTE")
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "CLIENTE"
  OWNER TO postgres;

  CREATE TABLE "PRODUTO"
(
  "ID_PRODUTO" integer NOT NULL DEFAULT nextval('"SEQ_PRODUTO"'::regclass),
  "DESCRICAO" character(30),
  "PRECO" numeric(10,2),
  "QTDADE" integer,
  CONSTRAINT "PK_PRODUTO" PRIMARY KEY ("ID_PRODUTO")
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "PRODUTO"
  OWNER TO postgres;

  CREATE TABLE "INTERACAO"
(
  "ID_INTERACAO" integer NOT NULL DEFAULT nextval('"SEQ_INTERACAO"'::regclass),
  "ID_CLIENTE" integer NOT NULL,
  "ID_PRODUTO" integer NOT NULL,
  "DATA" timestamp with time zone NOT NULL,
  CONSTRAINT "PK_INTERACAO" PRIMARY KEY ("ID_INTERACAO"),
  CONSTRAINT "FK_CLIENTE_INTERACAO" FOREIGN KEY ("ID_CLIENTE")
      REFERENCES "CLIENTE" ("ID_CLIENTE") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_PRODUTO_INTERACAO" FOREIGN KEY ("ID_PRODUTO")
      REFERENCES "PRODUTO" ("ID_PRODUTO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "INTERACAO"
  OWNER TO postgres;

  CREATE TABLE "VENDA"
(
  "ID_VENDA" integer NOT NULL DEFAULT nextval('"SEQ_VENDA"'::regclass),
  "ID_CLIENTE" integer NOT NULL,
  "DATA" timestamp with time zone NOT NULL,
  "TOTAL" numeric(10,2),
  CONSTRAINT "PK_VENDA" PRIMARY KEY ("ID_VENDA"),
  CONSTRAINT "FK_CLIENTE_VENDA" FOREIGN KEY ("ID_CLIENTE")
      REFERENCES "CLIENTE" ("ID_CLIENTE") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "VENDA"
  OWNER TO postgres;

  CREATE TABLE "VENDA_ITEM"
(
  "ID_VENDA_ITEM" integer NOT NULL DEFAULT nextval('"SEQ_VENDA_ITEM"'::regclass),
  "ID_VENDA" integer NOT NULL,
  "ID_PRODUTO" integer NOT NULL,
  "TOTAL" numeric(10,2),
  "QTDADE" integer,
  CONSTRAINT "PK_VENDA_ITEM" PRIMARY KEY ("ID_VENDA_ITEM"),
  CONSTRAINT "FK_PRODUTO_ITEM" FOREIGN KEY ("ID_PRODUTO")
      REFERENCES "PRODUTO" ("ID_PRODUTO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_VENDA_ITEM" FOREIGN KEY ("ID_VENDA")
      REFERENCES "VENDA" ("ID_VENDA") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "VENDA_ITEM"
  OWNER TO postgres;

  
  
  